# Generated by Django 4.2.7 on 2023-12-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamprofile",
            name="email_id",
            field=models.EmailField(max_length=254),
        ),
    ]
